package repository;

import api.PokemonApi;
import api.PokemonParser;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonParser;
import connection.DatabaseConnection;
import model.Movimento;
import model.Pokemon;
import enums.Tipo;

import java.sql.*;
import java.util.*;
import java.util.stream.Collectors;

public class PokemonRepository {

    private final PokemonApi api;
    private final PokemonParser parser;

    public PokemonRepository() throws SQLException {
        this.api = new PokemonApi();
        this.parser = new PokemonParser(api);
        criarTabelas();
    }


    public void criarTabelas() throws SQLException {
        try (Connection conn = DatabaseConnection.getConnection();
             Statement stmt = conn.createStatement()) {

            stmt.execute("""
                        CREATE TABLE IF NOT EXISTS pokemon (
                            id      INTEGER PRIMARY KEY,
                            nome    VARCHAR(100) NOT NULL,
                            vida    INTEGER NOT NULL,
                            nivel   INTEGER NOT NULL,
                            tipos   VARCHAR(100) NOT NULL
                        )
                    """);

            stmt.execute("""
                        CREATE TABLE IF NOT EXISTS movimento (
                            id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome      VARCHAR(100) NOT NULL,
                            dano      INTEGER NOT NULL,
                            tipo      VARCHAR(50)  NOT NULL,
                            pp_atual  INTEGER NOT NULL,
                            pp_maximo INTEGER NOT NULL,
                            precisao  INTEGER NOT NULL
                        )
                    """);

            stmt.execute("""
                        CREATE TABLE IF NOT EXISTS pokemon_movimento (
                            pokemon_id  INTEGER NOT NULL,
                            movimento_id INTEGER NOT NULL,
                            PRIMARY KEY (pokemon_id, movimento_id),
                            FOREIGN KEY (pokemon_id)   REFERENCES pokemon(id),
                            FOREIGN KEY (movimento_id) REFERENCES movimento(id)
                        )
                    """);

            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS jogador (
                        id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome        VARCHAR(100) NOT NULL,
                        pokemon_id  INTEGER NOT NULL,
                        vida_atual  INTEGER NOT NULL,
                        nivel_atual INTEGER NOT NULL,
                        pocoes      INTEGER NOT NULL,
                        FOREIGN KEY (pokemon_id) REFERENCES pokemon(id)
                    )
                    """);
            stmt.close();
        }
    }

    public void salvar(Pokemon pokemon) throws SQLException {
        try (Connection conn = DatabaseConnection.getConnection()) {
            try {
                salvarPokemon(conn, pokemon);
                for (Movimento movimento : pokemon.getMovimentos()) {
                    int movimentoId = salvarMovimento(conn, movimento);
                    vincularMovimento(conn, pokemon.getId(), movimentoId);
                }
                conn.commit();
            } catch (SQLException e) {
                conn.rollback();
                throw e;
            }
        }
    }

    private void salvarPokemon(Connection conn, Pokemon pokemon) throws SQLException {
        String sql = """
                    MERGE INTO pokemon (id, nome, vida, nivel, tipos)
                    KEY(id)
                    VALUES (?, ?, ?, ?, ?)
                """;
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, pokemon.getId());
            stmt.setString(2, pokemon.getNome());
            stmt.setInt(3, pokemon.getVida());
            stmt.setInt(4, pokemon.getNivel());
            stmt.setString(5, tiposParaString(pokemon.getTipos()));
            stmt.executeUpdate();
        }
    }

    private int salvarMovimento(Connection conn, Movimento movimento) throws SQLException {
        String sql = """
                    INSERT INTO movimento (nome, dano, tipo, pp_atual, pp_maximo, precisao)
                    VALUES (?, ?, ?, ?, ?, ?)
                """;
        try (PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            stmt.setString(1, movimento.getNome());
            stmt.setInt(2, movimento.getDano());
            stmt.setString(3, movimento.getTipo().name());
            stmt.setInt(4, movimento.getPpAtual());
            stmt.setInt(5, movimento.getPpMaximo());
            stmt.setInt(6, movimento.getPrecisao());
            stmt.executeUpdate();

            ResultSet keys = stmt.getGeneratedKeys();
            keys.next();
            return keys.getInt(1);
        }
    }

    private void vincularMovimento(Connection conn, int pokemonId, int movimentoId) throws SQLException {
        String sql = "INSERT INTO pokemon_movimento (pokemon_id, movimento_id) VALUES (?, ?)";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, pokemonId);
            stmt.setInt(2, movimentoId);
            stmt.executeUpdate();
        }
    }

    private String tiposParaString(List<Tipo> tipos) {
        return tipos.stream()
                .map(Tipo::name)
                .collect(Collectors.joining(","));
    }

    public List<Pokemon> buscarTodos() throws SQLException {
        String sql = """
                    SELECT p.id, p.nome, p.vida, p.nivel, p.tipos,
                           m.id AS mov_id, m.nome AS mov_nome, m.dano, m.tipo,
                           m.pp_atual, m.pp_maximo, m.precisao
                    FROM pokemon p
                    LEFT JOIN pokemon_movimento pm ON pm.pokemon_id = p.id
                    LEFT JOIN movimento m ON m.id = pm.movimento_id
                    ORDER BY p.id
                """;

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            Map<Integer, Pokemon> mapa = new LinkedHashMap<>();

            while (rs.next()) {
                int id = rs.getInt("id");

                if (!mapa.containsKey(id)) {
                    List<Tipo> tipos = stringParaTipos(rs.getString("tipos"));
                    Pokemon p = new Pokemon(id, rs.getString("nome"), tipos,
                            rs.getInt("vida"), rs.getInt("nivel"),
                            new ArrayList<>());
                    mapa.put(id, p);
                }

                if (rs.getString("mov_nome") != null) {
                    Tipo tipo = Tipo.valueOf(rs.getString("tipo"));
                    Movimento m = new Movimento(
                            rs.getString("mov_nome"),
                            rs.getInt("dano"),
                            tipo,
                            rs.getInt("pp_atual"),
                            rs.getInt("pp_maximo"),
                            rs.getInt("precisao")
                    );
                    mapa.get(id).getMovimentos().add(m);
                }
            }
            return new ArrayList<>(mapa.values());
        }
    }

    private List<Tipo> stringParaTipos(String tipos) {
        return Arrays.stream(tipos.split(","))
                .map(Tipo::valueOf)
                .collect(Collectors.toList());
    }

    public void popular() throws Exception {
        System.out.println("Buscando lista de pokémons...");
        String json = api.get("pokemon?limit=150");

        JsonArray results = JsonParser.parseString(json)
                .getAsJsonObject()
                .getAsJsonArray("results");

        int total = results.size();
        for (int i = 0; i < total; i++) {
            JsonElement el = results.get(i);
            String url = el.getAsJsonObject().get("url").getAsString();
            String nome = el.getAsJsonObject().get("name").getAsString();
            Thread.sleep(1200);
            try {
                System.out.printf("[%d/%d] Salvando %s...%n", i + 1, total, nome);
                String pokemonJson = api.getUrl(url);
                Pokemon pokemon = parser.parserPokemon(pokemonJson);
                salvar(pokemon);
            } catch (Exception e) {
                System.out.println("Erro ao salvar " + nome + ": " + e.getMessage());
            }
        }
        System.out.println("Concluído!");
    }

    public Pokemon buscarPorId(int id) throws SQLException {
        String sql = "SELECT id, nome, vida, nivel, tipos FROM pokemon WHERE id = ?";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, id);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                List<Tipo> tipos = stringParaTipos(rs.getString("tipos"));
                return new Pokemon(
                        rs.getInt("id"),
                        rs.getString("nome"),
                        tipos,
                        rs.getInt("vida"),
                        rs.getInt("nivel"),
                        new ArrayList<>()
                );
            }
            return null;
        }
    }

    public List<Pokemon> buscarAleatorios() throws SQLException {
        int quantidade = 3;
        List<Pokemon> todos = buscarTodos();
        Collections.shuffle(todos);
        return todos.subList(0, Math.min(quantidade, todos.size()));
    }
}